### ISSUE TITLE
Name tag not shown

### ISSUE THREAD

**Issue by MrPistachios** [PyvesB/PetMaster#10]
Hello, after installing the plugin the name tag of named animals no longer show on newly tamed pets.
Is there a way to be able to show the name tags again?

**Comment by PyvesB** [comment]
Hello @MrPistachios !

I am not able to reproduce with Pet Master 1.8.2 and Spigot 1.12.2. I'm quite surprised anyway, as Pet Master doesn't alter the name nor any other properties of pets, apart from their owners. 😉 

Cheers,

Pyves

**Comment by MrPistachios** [comment]
Very strange, when the animals are named and not tamed the name shows up from the name tag.
If the animal is tamed and then named with a name tag it doesn't show up but it does show the owners name.

We are using pet master with the holographic displays plugin as well
