### ISSUE TITLE
[Request] Option to disable in certain worlds

### ISSUE THREAD

**Issue by TheWranger** [PyvesB/PetMaster#11]
An option in the configuration that would allow for disabling in certain worlds. Very useful if we have a mob arena or some custom minigame in a world and want to avoid compatibility issues with PetMaster.

**Comment by PyvesB** [comment]
Hello @TheWranger,

Thanks for your suggestion. Do you have any programming knowledge? Would you like to submit a pull request? 😃 

Cheers,

Pyves
