### ISSUE TITLE
1.13?

### ISSUE THREAD

**Issue by TAfirehawk** [PyvesB/PetMaster#12]
Does this work in 1.13.X?

**Comment by PyvesB** [comment]
Hey @TAfirehawk ,

I don't see any compiler errors when switching to Minecraft 1.13, so I expect Pet Master to just work. We would only need to add `api-version: 1.13` to _plugin.yml_ to prevent the server from enabling any backwards-compatibility measures. This should not have any impact apart from possibly saving a tiny bit of performance. 😉 

Cheers,

Pyves

**Comment by TAfirehawk** [comment]
I hadn't added it to AACH before so I was just making a note in here.  I figured it would be pretty easy :)

**Comment by PyvesB** [comment]
Done, will release this minor change in the coming days. ^^
