### ISSUE TITLE
Option to toggle pet damage

### ISSUE THREAD

**Issue by ZaHecc** [PyvesB/PetMaster#13]
The plugin is very helpful!
Although I wish there was an option to toggle if your pets can be hurt by other people!

**Comment by PyvesB** [comment]
Hello @ZaHecc ,

Thanks for your suggestion. Do you have any programming knowledge? Would you like to submit a pull request? 😃

Cheers,

Pyves

**Comment by ZaHecc** [comment]
I have no programming knowledge

**Comment by lss233** [comment]
Hope this PR #14 helps.

**Comment by ZaHecc** [comment]
Thank you :)
