### ISSUE TITLE
Translation into german - Lang_de

### ISSUE THREAD

**Issue by ToxicShocks** [PyvesB/PetMaster#15]
Hello, 
thx for that plugin. Here are my german translation for that plugin (no gramma mistakes :P).
Hope you enjoy it!
It would be nice, if the pets had special effects (like power, fortune etc.)

Best regards,
[lang_de.zip](https://github.com/PyvesB/PetMaster/files/2281533/lang_de.zip)

Shotpirat - Hyperion Oldschool Minecraft Germany

**Comment by PyvesB** [comment]
Hello @ToxicShocks ,

Thanks for the translation! Would you like to submit it as a pull request? Simply navigate [here](https://github.com/PyvesB/PetMaster/tree/master/src/main/resources) and click "Create new file". You will appear as the author in the Git history by doing so. 😉 

Cheers,

Pyves
