### ISSUE TITLE
Setting ownership to yourself

### ISSUE THREAD

**Issue by MariChally** [PyvesB/PetMaster#16]
Hi,

I was wondering if you could add a permission to set the owner of a pet to myself? I run a shelter on a server but even with petm admin perms I can't set the owner of a pet to myself so I have to kill the pet and spawn in a new one. I might also just be misunderstanding things. If there's already a way to do that please tell me. 

Of course it would be absolutely fabulous if there was instead a command to automatically teleport a dog to a region, so I could use something like /petm teleport kennel1 and right click them. But that's obviously a much more complicated thing. Just having a permission for setting the owner to myself would work perfectly fine.

Thanks a lot, the plugin is awesome!

**Comment by PyvesB** [comment]
Hello @MariChally,

Normally permission `petmaster.admin` should allow to do that, have you set it up properly? What error message are you getting?

Cheers,

Pyves
