### ISSUE TITLE
CMI integration

### ISSUE THREAD

**Issue by ludvdber** [PyvesB/PetMaster#17]
Hello :)
would it be possible to use this plugin for holograms as well? [(CMI link)](https://www.spigotmc.org/resources/cmi-ranks-kits-portals-essentials-mysql-sqlite-bungeecord.3742/ ).
I find it more complete than holographic display for my use and it would be a shame to have two plugins doing the same thing :/

**Comment by PyvesB** [comment]
Hello @ludvdber,

Thanks for your suggestion. Nevertheless, I tagged the author of CMI on [another issue in Advanced Achievements](https://github.com/PyvesB/AdvancedAchievements/issues/357), but unfortunately there never was any reaction or acknowledgement of any kind. This feature is therefore unlikely to be added.

Cheers,

Pyves

**Comment by ludvdber** [comment]
Hi,

I understand. Thanks for your answer.  

cheers,
