### ISSUE TITLE
[Suggestion] Disable messages by entity

### ISSUE THREAD

**Issue by Blackyvk** [PyvesB/PetMaster#2]
Add an option in the config to disable showing who owns X type of pet completely

horse: disable
wolf: enabled 

and a permission so only certain groups can see it (if enabled in the config)

petmaster.showowner - allow to see who owns any pet (enabled by default)
petmaster.showowner.horse  - (negate to disable)

Something like that...

**Comment by PyvesB** [comment]
Hello,

Work was completed regarding your suggestion (both configuration options and permissions). If you want to give it a try, I can compile a _jar_ file for you, otherwise simply wait a few days/weeks until I release the next official version. ;-)

Cheers,

Pyves

**Comment by Blackyvk** [comment]
Thanks, i compiled it myself but i got this error https://hastebin.com/alujowohok.css I dont know if it was a mistake by me, i already changed the config files.

**Comment by PyvesB** [comment]
Sorry about that. It should now be fixed.
