### ISSUE TITLE
Installing Plugin to Minehut

### ISSUE THREAD

**Issue by jayuhyee** [PyvesB/PetMaster#22]
I was wondering if it were possible to install this plugin on Minehut?  If so, how?  The files are .class files which aren't allowed which would also mean I would need a completely different download for technically 98% of the files from the extracted .jar file.  Thanks in advance.

**Comment by PyvesB** [comment]
Hello @jayuhyee ,

I don't actually know what Minehut is. The source code is fully available in this repository, so I'm guessing you could use it to do what you want?

Cheers,

Pyves
