### ISSUE TITLE
Console Error after typing /petmaster (1.14.1)

### ISSUE THREAD

**Issue by HyperlyBola** [PyvesB/PetMaster#24]
21.05 17:01:42 [Server] INFO EXPbountyhunter issued server command: /petmaster
21.05 17:01:42 [Server] ERROR null
21.05 17:01:42 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'petmaster' in plugin PetMaster v1.9.4
21.05 17:01:42 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.14.1.jar:git-Paper-32]
21.05 17:01:42 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.1.jar:git-Paper-32]
21.05 17:01:42 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:736) ~[patched_1.14.1.jar:git-Paper-32]
21.05 17:01:42 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1826) ~[patched_1.14.1.jar:git-Paper-32]
21.05 17:01:42 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1634) ~[patched_1.14.1.jar:git-Paper-32]
21.05 17:01:42 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.1.jar:git-Paper-32]
21.05 17:01:42 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.1.jar:git-Paper-32]
21.05 17:01:42 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.1.jar:git-Paper-32]
21.05 17:01:42 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.1.jar:git-Paper-32]
21.05 17:01:42 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.1.jar:git-Paper-32]
21.05 17:01:42 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.1.jar:git-Paper-32]
21.05 17:01:42 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.1.jar:git-Paper-32]
21.05 17:01:42 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:995) ~[patched_1.14.1.jar:git-Paper-32]
21.05 17:01:42 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:988) ~[patched_1.14.1.jar:git-Paper-32]
21.05 17:01:42 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.1.jar:git-Paper-32]
21.05 17:01:42 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:971) ~[patched_1.14.1.jar:git-Paper-32]
21.05 17:01:42 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:906) ~[patched_1.14.1.jar:git-Paper-32]
21.05 17:01:42 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
21.05 17:01:42 [Server] INFO Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
21.05 17:01:42 [Server] INFO at com.hm.petmaster.particle.FancyMessageSender.constructHoverableCommandMessageJson(FancyMessageSender.java:243) ~[?:?]
21.05 17:01:42 [Server] INFO at com.hm.petmaster.particle.FancyMessageSender.sendHoverableCommandMessage(FancyMessageSender.java:65) ~[?:?]
21.05 17:01:42 [Server] INFO at com.hm.petmaster.command.HelpCommand.sendJsonClickableHoverableMessage(HelpCommand.java:96) ~[?:?]
21.05 17:01:42 [Server] INFO at com.hm.petmaster.command.HelpCommand.getHelp(HelpCommand.java:30) ~[?:?]
21.05 17:01:42 [Server] INFO at com.hm.petmaster.PetMaster.onCommand(PetMaster.java:281) ~[?:?]
21.05 17:01:42 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.1.jar:git-Paper-32]
21.05 17:01:42 [Server] INFO ... 17 more
21.05 17:01:42 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils
21.05 17:01:42 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_201]
21.05 17:01:42 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.14.1.jar:git-Paper-32]
21.05 17:01:42 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.1.jar:git-Paper-32]
21.05 17:01:42 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_201]
21.05 17:01:42 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]
21.05 17:01:42 [Server] INFO at com.hm.petmaster.particle.FancyMessageSender.constructHoverableCommandMessageJson(FancyMessageSender.java:243) ~[?:?]
21.05 17:01:42 [Server] INFO at com.hm.petmaster.particle.FancyMessageSender.sendHoverableCommandMessage(FancyMessageSender.java:65) ~[?:?]
21.05 17:01:42 [Server] INFO at com.hm.petmaster.command.HelpCommand.sendJsonClickableHoverableMessage(HelpCommand.java:96) ~[?:?]
21.05 17:01:42 [Server] INFO at com.hm.petmaster.command.HelpCommand.getHelp(HelpCommand.java:30) ~[?:?]
21.05 17:01:42 [Server] INFO at com.hm.petmaster.PetMaster.onCommand(PetMaster.java:281) ~[?:?]
21.05 17:01:42 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.1.jar:git-Paper-32]

**Comment by PyvesB** [comment]
Hello @HyperlyBola,

That's odd, Paper Spigot seems to be missing Apache commons-lang. Have you tried stopping and restarting the server completely? Are you using the very latest version of Paper Spigot?

Cheers,

Pyves

**Comment by HyperlyBola** [comment]
I'm using the latest version and I have restarted a few times, not sure what else to do about it.

**Comment by PyvesB** [comment]
Should be fixed by a5cf36c810fae32a519d2741cbfe837b55f984d1. Version 1.9.5 will be released soon, stay tuned. 😉
