### ISSUE TITLE
"Disable Player Damage" for Individual mobs

### ISSUE THREAD

**Issue by JMCY26** [PyvesB/PetMaster#25]
DisablePlayerDamage: True/False is okay... but if someone sets their wolf on you, you cannot fight back.

Could you make a break down below each mob, under Displaydog, DisplayCat, DisplayHorse etc, a Disable Damage for each mob individually, so I can disable Player damage myself for Cats, Horses, Llamas, parrots but not Dogs?

That way all nonaggressive animals are protected & players can still attack dogs to protect themselves.

Thanks

**Comment by PyvesB** [comment]
Hello @JMCY26 ,

This seems like a reasonable feature request, I'll see what I can do in the coming weeks. 😉 

Cheers,

Pyves

**Comment by JMCY26** [comment]
Thank you, would really appreciate that as it's highly requested on our server.

Thanks!

**Comment by PyvesB** [comment]
I've implemented a new `enableAngryMobPlayerDamage` configuration parameter that should do the trick. Would you like to give this beta version a try?

[PetMaster.zip](https://github.com/PyvesB/PetMaster/files/3317952/PetMaster.zip)

**Comment by JMCY26** [comment]
I will test this now, thank you

**Comment by JMCY26** [comment]
> I've implemented a new `enableAngryMobPlayerDamage` configuration parameter that should do the trick. Would you like to give this beta version a try?
> 
> [PetMaster.zip](https://github.com/PyvesB/PetMaster/files/3317952/PetMaster.zip)

I have now tested this and works great. Aggressive pet wolves can be killed, everything else not. Perfect!

**Comment by PyvesB** [comment]
Awesome! Will release officially later in the week, probably alongside some other small improvements. Closing. 😉
