### ISSUE TITLE
[Request] More mobs? Naming?

### ISSUE THREAD

**Issue by Zijuna** [PyvesB/PetMaster#27]
I like the plugin, but I would really like an option to configure which mobs are petifiable and which aren't. Maybe even determine which players can petify which mobs?

Also, could there be a way of naming the pets?
(Maybe a command for naming a pet that queries a right-click on a mob and if the owner is the one issuing the command then the NBT tag for the creatures name gets changed?)

**Comment by PyvesB** [comment]
Hello @Zijuna,

Sure, I could add configuration options/permissions to determine which pets can be tamed and which can't.

Naming is normally handled by name tags, I want to avoid duplicating the functionality in the plugin. 😉 

Cheers,

Pyves
