### ISSUE TITLE
Unable to add to Aternos Server

### ISSUE THREAD

**Issue by LarkspurRx** [PyvesB/PetMaster#32]
I've been able to add other plugins fine to my Aternos server, but when I click the version to add Pet Master to my server, it won't show up in my server files or help commands in game. I was wondering if it just doesn't do that or if I'm doing something wrong.

**Comment by PyvesB** [comment]
Hello @LarkspurRx! Are there any errors in the console?

**Comment by LarkspurRx** [comment]
Hello! There were no errors that I could find when looking at the console. As far as I know it reacts as though it's adding the plugin when I go to add it, but nothing shows up as far as in the files and log.

**Comment by PyvesB** [comment]
So the server isn't even trying to load the plugin? Have you put it in the right _plugins_ folder?
