### ISSUE TITLE
Setting Ownership to existing tamed animals as Admin

### ISSUE THREAD

**Issue by Hayden2006** [PyvesB/PetMaster#4]
I added this plugin to an existing world which has many tamed horses and animals already. A lot of them are tame with no owner which means nobody will ever own them and transferring ownership is impossible. We need an admin permission and command to set existing tamed animals to a person of the admin's choice (including that admin's own animals). It should be a direct override so that animals with owners can be changed too.

**Comment by PyvesB** [comment]
Hello,

The _petmaster.admin_ should already allow to do this. Does it not work as expected?

Cheers,

Pyves

**Comment by Hayden2006** [comment]
My server is kind of small, I run it alone as well as play. I have a lot of my own tamed horses that the plugin doesn't recognize as my own. I can't setowner to myself. Not sure if I can transfer an unowned trained horse to another player yet, I'll check that next time someone comes on. I don't have the admin node as a player, and when I try the command then it says I can't set to myself. I set myself as an OP and the command output says to click on one of my own pets to change its owner, however, when I do nothing happens. OP gets all nodes doesn't it? Seems to get all the other ones anyways.  

Also side note, I can right click on a tame horse to get on with anything in my hand, but a wild horse requires an empty hand. Has that always been a thing?

**Comment by PyvesB** [comment]
I'm confused about the fact that you can have tamed animals without an owner. Could you please try this test version I built and see if it helps? Not guaranteed to be bug-free. :-)

[PetMaster-1.6.2.zip](https://github.com/PyvesB/PetMaster/files/1297506/PetMaster-1.6.2.zip)

**Comment by Hayden2006** [comment]
It's a matter of having tamed horses before having your plugin. Unless it doesn't tell me if it's my own horse? I'll definitely do some testing asap to see if I can narrow things down.

**Comment by PyvesB** [comment]
Well no, ownership is not displayed to the owner  of the pet.
