### ISSUE TITLE
Update more pets !!

### ISSUE THREAD

**Issue by FarLokus** [PyvesB/PetMaster#41]
Hi,
I am FarLokus and have new issues here.

Maybe you can give an update for custom pets?
Maybe user can create pets for all. (chicken, zompie babys, ...)
Maybe with name tags and pemissions?

**Comment by PyvesB** [comment]
Hello @FarLokus,

Turning all mobs into proper pets would probably be quite tricky, I've got a feeling there would be limitations on the Minecraft/Spigot API side. Though if something wants to give this a go, feel free to submit a pull request. 😉

**Comment by FarLokus** [comment]
ok
