### ISSUE TITLE
release animals to the wild

### ISSUE THREAD

**Issue by Hayden2006** [PyvesB/PetMaster#5]
It would be cool to be able to release your own owned animals back to the wild. (also with an admin perm/command to set anyone's animals free, helps with non returning players).

**Comment by PyvesB** [comment]
Hello,

Seems like a decent suggestion, I will add that to the plugin. ;-)

Cheers,

Pyves

**Comment by Hayden2006** [comment]
I wish I knew how to make plugins man, I come up with cool stuff sometimes. :P

**Comment by PyvesB** [comment]
Done! The new command will be available in the upcoming 1.7 release of PetMaster! ;-)
