### ISSUE TITLE
Action bars doesn't work on 1.17.x

### ISSUE THREAD

**Issue by iOshawott** [PyvesB/PetMaster#52]
We're getting
`[20:13:19 WARN]: [PetMaster] Errors while trying to display action bar message for pet ownership.`
on console while using latest on 1.17.x

**Comment by PyvesB** [comment]
Hello @iOshawott ! 👋🏻 

Yes, I'm aware of this issue. However, I've got very limited time to dedicate to this project nowadays, see #45.

**Comment by PyvesB** [comment]
This has been fixed and will soon be released.
