### ISSUE TITLE
Formatting error

### ISSUE THREAD

**Issue by oguh43** [PyvesB/PetMaster#55]
Shift right clicking a owned dog displays "&OPet is owned by"...

**Comment by BigTallahasee** [comment]
@oguh43 Hello I am sorry to hear that you are having issues. I will look into this and get it resolved. If you need anything else feel free to reach out and let me know.

**Comment by BigTallahasee** [comment]
@oguh43 I have just released a new update that should fix this issue. Thank you for reporting and if you have anymore issues feel free to reach out again :D

**Comment by oguh43** [comment]
> @oguh43 I have just released a new update that should fix this issue. Thank you for reporting and if you have anymore issues feel free to reach out again :D

Thanks :)

**Comment by PyvesB** [comment]
Good stuff on getting your first update through @BigTallahasee ! :+1:

Two thoughts/observations:
* the changelog on Bukkit seems broken. You probably can't copy-paste from Spigot directly, or maybe you need to copy-paste when in edit mode.
* I would strongly recommend pushing changes to GitHub in small separate commits. It would be good to keep the project open-source and collaborative. Furthermore, the update checker relies on data from GitHub.

The workflow I used on this project was the following:
* push all changes to GitHub as I went along, but only prepare the `Increase version number to xxx` locally.
* submit the update to Bukkit.
* wait until the update is accepted and live.
* submit the update to Spigot by using the Bukkit download link - it's nice to point to the same unique download source (and also artificially increase the Bukkit download statistics :)).
* push the increase version commit. At this point, users will be notified about the update and will be able to download on either Bukkit or Spigot.
* do a tagged release via the GitHub UI.

Of course feel free to tune with what works best for you. Let me know if you have any questions.

**Comment by BigTallahasee** [comment]
Thank you I will keep all of that in mind and start working towards that becoming a habit . :D

**Comment by seema84** [comment]
Version 1.12.5 don't fix this issue.

**Comment by BigTallahasee** [comment]
@seema84  I apologize that your are still having this issue. When I was doing testing there wasn't any formatting errors when I uploaded the Update. Can you help me out by giving me a way to duplicate this issue? Thank you in advance have a great rest of your day!

**Comment by seema84** [comment]
Hey @BigTallahasee, thanks for your reply.

I dont know if its relevant, i use the germany language file. https://github.com/PyvesB/PetMaster/blob/master/src/main/resources/lang-DE.yml

When I right-click on a wolf (not owned by me), for example, the first character displayed in the actionbar is "&O".

**Comment by seema84** [comment]
its in 
https://github.com/PyvesB/PetMaster/blob/4db543d9ede978367130ef93575e4f1d35c1e1c0/src/main/java/com/hm/petmaster/listener/PlayerInteractListener.java

		if (actionBarMessage) {
			try {
				FancyMessageSender.sendActionBarMessage(player, "&o" + ChatColor.GRAY
						+ plugin.getPluginLang().getString("petmaster-action-bar", "Pet owned by ") + ChatColor.GOLD
						+ owner.getName() + healthInfo);
			} catch (Exception e) {
				plugin.getLogger().warning("Errors while trying to display action bar message for pet ownership.");
			}

**Comment by PyvesB** [comment]
Switching to `§o` instead of `&o` in the source code should fix the issue.

**Comment by BigTallahasee** [comment]
> Switching to `§o` instead of `&o` in the source code should fix the issue.

I tried switching it here on github. It says that I have to be on the branch to make or propose changes

**Comment by PyvesB** [comment]
The change seems to have gone through: f293edbcfdecf5ed0720089c8e693b649e5b5fdd 👍🏻 

You can also use GitHub desktop to help you out (https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/committing-and-reviewing-changes-to-your-project), or do things through the command line. This training is quite fun and useful: https://learngitbranching.js.org/

**Comment by BigTallahasee** [comment]
Thank you :D
