### ISSUE TITLE
'&o' in front of ActionBarMassage

### ISSUE THREAD

**Issue by Blautee** [PyvesB/PetMaster#57]
When rightclicking a Pet that is not mine, I see the ActionBar, which shows owner and health, formatted perfectly fine with colors. But in front of this message, a '&o' appears, which apperently is not translated into a color correctly (and is also not part of any config). I quickly checked your source code and found, that you can probably remove the '_"§o" +_ ' in _line 298_ of your _PlayerInteractListener.java_, since the formatting with '_ChatColor.GRAY_' seems to be working fine on its own. Or, if its something I did wrong setting up your awesome plugin, feel free to tell me :D

**Comment by BigTallahasee** [comment]
I am sorry that you are having this issue. I thought that 1.12.5 fix would fix it. But shortly after 1.12.5 we did get it fixed as of Issue #55 and should defiently be fixed when the next update drops.
