### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by seema84** [PyvesB/PetMaster#59]
I get some errors when compiling the plugin.

Edit: I only get the errors in a windows cmd shell.
https://github.com/PyvesB/PetMaster/issues/59#issuecomment-974842269

**Comment by BigTallahasee** [comment]
Compile errorrs???? I am not getting any compile errors at all so can  you explain what errors you are getting???

**Comment by BigTallahasee** [comment]
![Screenshot 2021-11-21 091926](https://user-images.githubusercontent.com/85016240/142767948-de56af28-ef4b-4ff4-a81c-05e8dce830fb.png)

**Comment by seema84** [comment]
try _mvn package_ or _mvn clean install_ in command line

**Comment by BigTallahasee** [comment]
![jfjf](https://user-images.githubusercontent.com/85016240/142768832-3cddeb0d-fe0b-4dbf-b618-fd4833c0f2ff.png)
Alright I did that but there still isn't any errors????

**Comment by BigTallahasee** [comment]
![Screenshot 2021-11-21 094644](https://user-images.githubusercontent.com/85016240/142768931-4f829d0a-6ae9-4fe6-83fe-c2aa6bd39c29.png)

**Comment by seema84** [comment]
![66](https://user-images.githubusercontent.com/2832339/142769046-8b6b0b9d-8e3b-4e72-91a1-923455ece870.PNG)

**Comment by seema84** [comment]
> ![jfjf] Alright I did that but there still isn't any errors????

I my shell I get some. In eclipse I have not tested it yet.

**Comment by BigTallahasee** [comment]
I would run it in eclipse I have ran the version I got and the one off github. I didn't receive any compilation errors and I have even thrown both copies into Mc and they both work so this has me stumped!

**Comment by seema84** [comment]
I just wanted to tell about it and help with that.
If you want I can also test it again in eclipse.

**Comment by BigTallahasee** [comment]
Yeah thank you for letting me know. Are you having errors in eclipse too. I want you to have a working copy as that was the previous owners requests!

**Comment by BigTallahasee** [comment]
Oh one more thing are you just using like the windows shell or is there a shell specifically I will look into no gurantees I will be able to figure it out but I can try atleast

**Comment by seema84** [comment]
Its the normal and old windows cmd shell.

**Comment by seema84** [comment]
> Are you having errors in eclipse too. 

In eclipse it works without problems.

**Comment by BigTallahasee** [comment]
Sounds good I have put it on my todo list
