### ISSUE TITLE
Right click, does not do a thing.

### ISSUE THREAD

**Issue by JoJonah34** [PyvesB/PetMaster#63]
I've recently installed your plugin to my server, but i can't assign a pet to owner by right clicking.
The commands run fine, but whenever i use /petm setowner {playername}, it says: "Right click on a pet to change its owner!".

The only thing is right click doesn't to anyting... so thats very strange xD

I hope you can help me with this and that it isn't just a stupid thing i'm missing.

Dear regards,

JoJonah

**Comment by Xaver106** [comment]
Are you the Owner of the pet? If so, you need to activate sending the messages to the Owner as well.
