### ISSUE TITLE
[Request] Allow Pets To Respawn If They Are Killed And/Or Make Them Immortal

### ISSUE THREAD

**Issue by SleepyCatten** [PyvesB/PetMaster#64]
Good day,

There is a datapack called the "Pet Respawning Pack":
https://www.planetminecraft.com/data-pack/dog-and-cat-respawning-pack/

This allows pets (cats, parrots and wolves) to respawn either on a bed or at 0,0, but does not function particularly well. (The respawns often take time.)

Would it kindly be possible to create something like this, so that tamed pets can never truly die? Perhaps have an option for players of where to respawn their pets the next morning if they die. (E.g., at spawn point; at their bed/anchor point; at 0,0).

Alternatively, an option to make them unkillable (at least for pets which cannot attack mobs) would be very welcome.

Kind regards

**Comment by BigTallahasee** [comment]
Hello sorry for a late response. I do currently have several different features that I am thinking about testing out that server owners will be able to choose from.
